# Generated by Django 4.0.4 on 2022-05-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
